'use client';
import { useEffect, useState } from 'react';
const money = n => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
const device = () => { let id = localStorage.getItem('eagleeye-device'); if (!id) { id = crypto.randomUUID(); localStorage.setItem('eagleeye-device', id); } return id; };
const supported = [{ symbol:'NVDA',name:'NVIDIA'},{symbol:'AAPL',name:'Apple'},{symbol:'MSFT',name:'Microsoft'},{symbol:'TSLA',name:'Tesla'},{symbol:'AMZN',name:'Amazon'},{symbol:'META',name:'Meta'},{symbol:'GOOGL',name:'Alphabet'},{symbol:'NFLX',name:'Netflix'},{symbol:'AMD',name:'AMD'},{symbol:'AVGO',name:'Broadcom'},{symbol:'ORCL',name:'Oracle'},{symbol:'CRM',name:'Salesforce'},{symbol:'INTC',name:'Intel'},{symbol:'PLTR',name:'Palantir'},{symbol:'JPM',name:'JPMorgan Chase'},{symbol:'V',name:'Visa'},{symbol:'WMT',name:'Walmart'},{symbol:'COST',name:'Costco'},{symbol:'DIS',name:'Disney'},{symbol:'UBER',name:'Uber'},{symbol:'NKE',name:'Nike'},{symbol:'KO',name:'Coca-Cola'},{symbol:'PEP',name:'PepsiCo'},{symbol:'LLY',name:'Eli Lilly'},{symbol:'UNH',name:'UnitedHealth'},{symbol:'XOM',name:'Exxon Mobil'},{symbol:'CAT',name:'Caterpillar'}];
export default function Home() {
  const [data, setData] = useState(null), [ticker, setTicker] = useState(''), [toast, setToast] = useState(''), [checking, setChecking] = useState(false), [pickerOpen, setPickerOpen] = useState(false), [remoteOptions, setRemoteOptions] = useState([]);
  const headers = () => ({ 'x-device-id': device(), 'content-type': 'application/json' });
  const load = async (force = false, background = false) => { try { const params = new URLSearchParams(); if (force) params.set('refresh', '1'); if (background) params.set('background', '1'); const r = await fetch(`/api/dashboard${params.size ? `?${params}` : ''}`, { headers: headers(), cache: 'no-store' }), out = await r.json(); if (!r.ok) throw new Error(out.error); setData(out); if (force) setToast('Live provider checked just now.'); } catch (e) { setToast(e.message || 'Market service unavailable.'); } finally { setChecking(false); } };
  useEffect(() => { load(); const timer = setInterval(() => load(false, true), 30000); return () => clearInterval(timer); }, []);
  useEffect(() => { const close = e => { const picker = document.querySelector('.ticker-picker'); if (picker && !picker.contains(e.target)) setPickerOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { if (ticker.length < 2) { setRemoteOptions([]); return; } const timer = setTimeout(async () => { try { const r = await fetch(`/api/search?q=${encodeURIComponent(ticker)}`), out = await r.json(); setRemoteOptions(r.ok ? out.results : []); } catch { setRemoteOptions([]); } }, 250); return () => clearTimeout(timer); }, [ticker]);
  const verify = () => { setChecking(true); load(true, true); };
  const add = async e => { e.preventDefault(); const r = await fetch('/api/watchlist', { method: 'POST', headers: headers(), body: JSON.stringify({ symbol: ticker }) }), out = await r.json(); setToast(r.ok ? `${out.item.symbol} added` : out.error); if (r.ok) setTicker(''); load(false, true); };
  const remove = async s => { await fetch(`/api/watchlist/${s}`, { method: 'DELETE', headers: headers() }); setToast(`${s} removed`); load(false, true); };
  const items = data?.items?.sort((a,b) => b.score-a.score) || [], focus = data?.changed?.length || 0, suggestions = ticker.length < 2 ? supported.slice(0, 8) : remoteOptions;
  return <><div className="aurora a"/><div className="aurora b"/><main><nav><div className="brand"><span className="mark">E</span>EagleEye</div><div className="nav-right"><span className="live-dot"/><span>Live quote provider</span><button className="avatar">EE</button></div></nav><section className="hero"><div><p className="eyebrow">YOUR MARKET, DISTILLED</p><h1>Don't scan the market.<br/><em>See what moved.</em></h1><p className="sub">EagleEye remembers your last visit and only brings forward the signals that earned attention.</p></div><div className="hero-stat"><span>ATTENTION QUEUE</span><strong>{data ? focus : '-'}</strong><small>signals need a look</small></div></section><section className="brief"><div className="brief-icon">*</div><div><p className="eyebrow">THE BRIEFING - SINCE YOUR LAST VISIT</p><h2>{!data ? 'Fetching live market data...' : focus ? `${focus} ${focus === 1 ? 'signal needs' : 'signals need'} your attention.` : 'Nothing material shifted. You are caught up.'}</h2><p>Live quotes refresh every 30 seconds; force-checks bypass the server cache.</p></div><button className="icon-btn" onClick={verify} disabled={checking}>{checking ? '...' : 'R'}</button></section>{data?.ledger?.length > 0 && <section className="ledger"><div className="ledger-head"><div><p className="eyebrow">THE CHANGE LEDGER</p><h3>What changed - and what to do next</h3></div><span>MEMORY-BASED</span></div><div className="signal-row">{data.ledger.map(x => <Signal key={x.symbol} x={x} verify={verify} checking={checking}/>)}</div></section>}<section className="toolbar"><div><h3>Your watchlist <span>{items.length}</span></h3><p>Sorted by relevance, not ticker alphabet.</p></div><form className="asset-form" onSubmit={add}><div className="ticker-picker"><input value={ticker} onFocus={() => setPickerOpen(true)} onChange={e => { setTicker(e.target.value.toUpperCase()); setPickerOpen(true); }} placeholder="Search company or ticker"/>{pickerOpen && <div className="ticker-options">{suggestions.length ? suggestions.map(x => <button type="button" key={x.symbol} onMouseDown={e => e.preventDefault()} onClick={() => { setTicker(x.symbol); setPickerOpen(false); }}><b>{x.symbol}</b><span>{x.name}</span></button>) : <p>No supported ticker found</p>}</div>}</div><button>Add asset <span>+</span></button></form></section>{toast && <div id="toast" className="show">{toast}</div>}<section className="grid">{items.map((x,i) => <Card key={x.symbol} x={x} i={i} remove={remove}/>)}</section><footer><span>Live US quote data via Finnhub - not investment advice</span><span>Last sync {data ? new Date(data.updatedAt).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' }) : '-'}</span></footer></main></>;
}
function Signal({ x, verify, checking }) { return <article className="signal"><div><b>{x.symbol}</b><span className={x.sinceSeen >= 0 ? 'up' : 'down'}>{x.sinceSeen >= 0 ? '+' : ''}{x.sinceSeen}% since check-in</span></div><p>{x.reasons[0] || x.catalyst}</p><footer><small>Confidence {x.confidence}%</small>{x.action === 'Verify feed' ? <button className="verify-btn" onClick={verify} disabled={checking}>{checking ? 'Checking...' : 'Verify feed'}</button> : x.action === 'Investigate now' ? <a className="investigate-link" href={`https://finance.yahoo.com/quote/${encodeURIComponent(x.symbol)}`} target="_blank" rel="noreferrer">Investigate now</a> : <strong>{x.action}</strong>}</footer></article>; }
function Card({ x, i, remove }) { const up = x.change >= 0, hot = x.score >= 80 || Math.abs(x.sinceSeen) >= 1; const label = x.freshness === 'delayed' ? 'DELAYED FEED' : x.freshness === 'closed' ? 'MARKET CLOSED' : hot ? 'WORTH A LOOK' : 'LIVE'; return <article className={`card ${hot ? 'focus' : ''}`} style={{ animationDelay: `${i * 60}ms` }}><div className="card-top"><div><div className="ticker">{x.symbol}</div><div className="company">{x.name}</div></div><span className={`pill ${hot ? 'hot' : ''}`}>{label}</span></div><div className="price-row"><span className="price">{money(x.price)}</span><span className={`change ${up ? 'up' : 'down'}`}>{up ? 'UP' : 'DOWN'} {up ? '+' : ''}{x.change.toFixed(2)}%</span></div><div className="card-bottom"><span className="insight">{x.range}</span><div className="meter"><i style={{ width: `${x.score}%` }}/></div></div><button className="delete" onClick={() => remove(x.symbol)}>x</button></article>; }
